# Generated by Django 5.1.6 on 2025-03-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_contact_us_alter_participant_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact_us',
            name='email',
            field=models.EmailField(default='no-email@example.com', max_length=254),
        ),
    ]
